//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBWebsite.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SBWDataEntities : DbContext
    {
        public SBWDataEntities()
            : base("name=SBWDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTS { get; set; }
        public virtual DbSet<APPLICANT> APPLICANTS { get; set; }
        public virtual DbSet<EMPLOYER> EMPLOYERs { get; set; }
        public virtual DbSet<JOB_APPLICANTS> JOB_APPLICANTS { get; set; }
        public virtual DbSet<JOB_CATEGORIES> JOB_CATEGORIES { get; set; }
        public virtual DbSet<JOB> JOBS { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<SKILL> SKILLS { get; set; }
        public virtual DbSet<STAFF> STAFFS { get; set; }
        public virtual DbSet<SUGGESTION> SUGGESTIONS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TIME> TIMEs { get; set; }
    }
}
