//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBWebsite.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYER
    {
        public EMPLOYER()
        {
            this.JOBS = new HashSet<JOB>();
        }
    
        public string USER_NAME { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string DESCRIPTIONS { get; set; }
        public string STAFF_APPROVE { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual STAFF STAFF { get; set; }
        public virtual ICollection<JOB> JOBS { get; set; }
    }
}
