//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBWebsite.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public ROLE()
        {
            this.ACCOUNTS = new HashSet<ACCOUNT>();
        }
    
        public int ROLE_SEQ { get; set; }
        public string ROLE_NAME { get; set; }
    
        public virtual ICollection<ACCOUNT> ACCOUNTS { get; set; }
    }
}
