//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBWebsite.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKILL
    {
        public SKILL()
        {
            this.APPLICANTS = new HashSet<APPLICANT>();
            this.JOBS = new HashSet<JOB>();
        }
    
        public int SKILL_SEQ { get; set; }
        public string SKILL_NAME { get; set; }
        public string DESCRIPTIONS { get; set; }
    
        public virtual ICollection<APPLICANT> APPLICANTS { get; set; }
        public virtual ICollection<JOB> JOBS { get; set; }
    }
}
