//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUGGESTION
    {
        public string USER_NAME { get; set; }
        public int JOBS_SEQ { get; set; }
        public int EVENT_SEQ { get; set; }
    
        public virtual APPLICANT APPLICANT { get; set; }
        public virtual JOB JOB { get; set; }
    }
}
