//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        public JOB()
        {
            this.JOB_APPLICANTS = new HashSet<JOB_APPLICANTS>();
            this.SUGGESTIONS = new HashSet<SUGGESTION>();
            this.JOB_CATEGORIES = new HashSet<JOB_CATEGORIES>();
            this.TIMEs = new HashSet<TIME>();
            this.SKILLS = new HashSet<SKILL>();
        }
    
        public int JOB_SEQ { get; set; }
        public string USER_NAME { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTIONS { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<int> CANDIDATE_QUANTITY { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<int> AGE { get; set; }
    
        public virtual EMPLOYER EMPLOYER { get; set; }
        public virtual ICollection<JOB_APPLICANTS> JOB_APPLICANTS { get; set; }
        public virtual ICollection<SUGGESTION> SUGGESTIONS { get; set; }
        public virtual ICollection<JOB_CATEGORIES> JOB_CATEGORIES { get; set; }
        public virtual ICollection<TIME> TIMEs { get; set; }
        public virtual ICollection<SKILL> SKILLS { get; set; }
    }
}
