//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBWebsite.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT
    {
        public APPLICANT()
        {
            this.JOB_APPLICANTS = new HashSet<JOB_APPLICANTS>();
            this.SUGGESTIONS = new HashSet<SUGGESTION>();
            this.JOB_CATEGORIES = new HashSet<JOB_CATEGORIES>();
            this.TIMEs = new HashSet<TIME>();
            this.SKILLS = new HashSet<SKILL>();
        }
    
        public string USER_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public int AGE { get; set; }
        public string linkCV { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ICollection<JOB_APPLICANTS> JOB_APPLICANTS { get; set; }
        public virtual ICollection<SUGGESTION> SUGGESTIONS { get; set; }
        public virtual ICollection<JOB_CATEGORIES> JOB_CATEGORIES { get; set; }
        public virtual ICollection<TIME> TIMEs { get; set; }
        public virtual ICollection<SKILL> SKILLS { get; set; }
    }
}
