//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME
    {
        public TIME()
        {
            this.APPLICANTS = new HashSet<APPLICANT>();
            this.JOBS = new HashSet<JOB>();
        }
    
        public int TIME_SEQ { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<APPLICANT> APPLICANTS { get; set; }
        public virtual ICollection<JOB> JOBS { get; set; }
    }
}
