USE [master]
GO

/****** Object:  Database [SBWebsite]    Script Date: 09/02/2015 20:42:56 ******/
DROP DATABASE [SBWebsite]
GO

/****** Object:  Database [SBWebsite]    Script Date: 09/02/2015 20:42:56 ******/
CREATE DATABASE [SBWebsite]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SBWebsite', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.HAITH2207\MSSQL\DATA\SBWebsite.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SBWebsite_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.HAITH2207\MSSQL\DATA\SBWebsite_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SBWebsite] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SBWebsite].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SBWebsite] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SBWebsite] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SBWebsite] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SBWebsite] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SBWebsite] SET ARITHABORT OFF 
GO

ALTER DATABASE [SBWebsite] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SBWebsite] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SBWebsite] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SBWebsite] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SBWebsite] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SBWebsite] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SBWebsite] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SBWebsite] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SBWebsite] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SBWebsite] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SBWebsite] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SBWebsite] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SBWebsite] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SBWebsite] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SBWebsite] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SBWebsite] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SBWebsite] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SBWebsite] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SBWebsite] SET RECOVERY FULL 
GO

ALTER DATABASE [SBWebsite] SET  MULTI_USER 
GO

ALTER DATABASE [SBWebsite] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SBWebsite] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SBWebsite] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SBWebsite] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SBWebsite] SET  READ_WRITE 
GO


